apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: demo
  labels:
    app: nginx-demo 
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx-demo 
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx:1.16.0 
        ports:
        - containerPort: 80
